require "rjava"

# Copyright (c) 2000, 2003 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
# IBM Corporation - initial API and implementation
module Org::Eclipse::Swt::Events
  module ControlListenerImports #:nodoc:
    class_module.module_eval {
      include ::Java::Lang
      include ::Org::Eclipse::Swt::Events
      include_const ::Org::Eclipse::Swt::Internal, :SWTEventListener
    }
  end
  
  # Classes which implement this interface provide methods
  # that deal with the events that are generated by moving
  # and resizing controls.
  # <p>
  # After creating an instance of a class that implements
  # this interface it can be added to a control using the
  # <code>addControlListener</code> method and removed using
  # the <code>removeControlListener</code> method. When a
  # control is moved or resized, the appropriate method will
  # be invoked.
  # </p>
  # 
  # @see ControlAdapter
  # @see ControlEvent
  module ControlListener
    include_class_members ControlListenerImports
    include SWTEventListener
    
    typesig { [ControlEvent] }
    # Sent when the location (x, y) of a control changes relative
    # to its parent (or relative to the display, for <code>Shell</code>s).
    # 
    # @param e an event containing information about the move
    def control_moved(e)
      raise NotImplementedError
    end
    
    typesig { [ControlEvent] }
    # Sent when the size (width, height) of a control changes.
    # 
    # @param e an event containing information about the resize
    def control_resized(e)
      raise NotImplementedError
    end
  end
  
end
